[tool.poetry]
name = "rust-game-server-docker"
version = "0.1.0"
description = ""
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
click = "8.1.7"
python-on-whales = "0.71.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.2.2"
pre-commit = "3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
