apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
type: Opaque
stringData:
  rconPassword: "{{ .Values.rustDedicatedServer.rconPassword }}"