apiVersion: v1
kind: Service
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: server-port
      port: 28015
      targetPort: server-port
      protocol: UDP
    - name: rcon-port
      port: 28016
      targetPort: rcon-port
      protocol: UDP
  selector:
    {{- include "rust.selectorLabels" . | nindent 4 }}
