apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  serviceName: {{ include "rust.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rust.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rust.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rust.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "+server.ip"
            - "0.0.0.0"
            - "+server.port"
            - "28015"
            - "+server.hostname"
            - {{ .Values.rustDedicatedServer.hostName }}
            - "+server.maxplayers"
            - {{ .Values.rustDedicatedServer.maxPlayers }}
            - "+server.worldsize"
            - {{ .Values.rustDedicatedServer.worldSize }}
            - "+server.gamemode"
            - "vanilla"
            - "+server.seed"
            - {{ .Values.rustDedicatedServer.seed }}
            - "+server.identity"
            - "dedicated"
            - "+rcon.ip"
            - "0.0.0.0"
            - "+rcon.port"
            - "28016"
            - "+rcon.password"
            - {{ .Values.rustDedicatedServer.rconPassword }}
            - "+rcon.web"
            - {{ .Values.rustDedicatedServer.rconWeb }}
            - "-logfile"
            - "/srv/rust/server/dedicated/logs/rust-server.log"
          ports:
            - name: server-port
              containerPort: 28015
              protocol: UDP
            - name: rcon-port
              containerPort: 28016
              protocol: UDP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: server-identity
              mountPath: "/srv/rust/server/dedicated"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: server-identity
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi