name: Pipeline

on: push

jobs:
  publish-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Publish Images to Docker Hub
        run: |
          if [ "$(date '+%u')" = "7" ] then echo "execute" fi
