name: Pipeline

on: push

jobs:
  set-environment-variables:
    runs-on: ubuntu-20.04
    steps:
      - name: Set environment variables
        run: |
          echo "{DATE}={$(date '+%Y-%m-%d')}" >> "$GITHUB_ENV"
          echo "{DAY_OF_WEEK}={$(date '+%u')}" >> "$GITHUB_ENV"

  code-quality:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Publish Images to Docker Hub
        run: |
          echo $DATE
          echo $DAY_OF_WEEK
