name: Publish Docker Image Manually

on:
  workflow_dispatch:

jobs:
  call-publish-docker-image:
    uses: ./.github/workflows/docker-image.yaml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
