name: Publish Docker Image

on:
  schedule:
    - cron: "0 1 1-7 * *"

jobs:
  publish-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Build and publish Images to Docker Hub every Friday
        run: |
          VERSION=$(date '+%Y-%m-%d')
          if [ "$(date '+%u')" = "5" ]; then echo $VERSION; fi
