name: Publish Docker Image Manually

on:
  workflow_dispatch:
    inputs:
      weekday:
        description: Weekday for execution
        type: string
        default: "5"

jobs:
  call-publish-docker-image:
    uses: ./.github/workflows/docker-image.yaml
    with:
      weekday: ${{ inputs.weekday }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
